AllCops:
  DisplayCopNames: true
  Exclude:
    - "db"
    - "config/routes.rb"
    - "**/*_schema.rb"
    - "node_modules"

Documentation:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "config/routes.rb"

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "**/*_schema.rb"

Metrics/ClassLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented


Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/EmptyLineAfterGuardClause:
  Enabled: false
