inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "coverage"
    - "tmp"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "config/routes.rb"

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 15
  Exclude:
    - "config/routes.rb"
    - "**/*_schema.rb"
    - "test/**/*"
    - "Vagrantfile"
    - "config/environments/*"
    - "**/*.rake"

Metrics/ClassLength:
  Max: 300

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - "bin/**/*"
    - "db/migrations"

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent
