# Based on https://github.com/airbnb/css
# SEE: https://github.com/brigade/scss-lint

severity: error

linters:
  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  LeadingZero:
    enabled: false

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: double_quotes

  NestingDepth:
    max_depth: 4

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase
    variable_convention: hyphenated_lowercase

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
