---
- name: "xkcd"
  url: "http://xkcd.com/rss.xml"
  processor: "rss"

- name: "oglaf"
  url: "http://oglaf.com/feeds/rss/"
  processor: "oglaf"
  normalizer: "oglaf"

- name: "phdcomics"
  url: "http://feeds.feedburner.com/PhdComics"
  processor: "rss"

- name: "commitstrip"
  url: "https://www.commitstrip.com/en/feed/"
  processor: "rss"

- name: "dilbert"
  url: "http://dilbert.com/feed"
  processor: "atom"

- name: "rllivejournal"
  url: "http://r-l.livejournal.com/data/rss"
  processor: "rss"
  normalizer: "livejournal"

- name: "nichtlustig-de"
  url: "http://static.nichtlustig.de/rss/nichtrss.rss"
  processor: "rss"

- name: "oatmeal"
  url: "http://feeds.feedburner.com/oatmealfeed"
  processor: "rss"

- name: "wumo"
  url: "http://wumo.com/wumo?view=rss"
  processor: "rss"

- name: "kamillalinder-medium"
  url: "https://medium.com/feed/@kamillalinder"
  processor: "rss"
  normalizer: "medium"

- name: "signalvnoise-medium"
  url: "https://m.signalvnoise.com/feed"
  processor: "rss"
  normalizer: "medium"

- name: "github-blog"
  url: "https://github.com/blog/all.atom"
  processor: "atom"

- name: "explosm-comics"
  url: "http://feeds.feedburner.com/Explosm"
  processor: "rss"

- name: "the-atlantic-photos"
  url: "http://feeds.feedburner.com/theatlantic/infocus"
  processor: "rss"

- name: "esquire-photos"
  url: "http://feeds.feedburner.com/esquire-ru"
  processor: "rss"

- name: "best-of-hacker-news"
  processor: "hacker_news"
  normalizer: "hacker_news"

- name: "reddit-worldnews"
  url: "https://www.reddit.com/r/worldnews/.rss"
  processor: "reddit"
  normalizer: "reddit"
