---
- name: "xkcd"
  url: "http://xkcd.com/rss.xml"
  processor: "rss"

- name: "oglaf"
  url: "http://oglaf.com/feeds/rss/"
  processor: "oglaf"
  normalizer: "oglaf"

- name: "phdcomics"
  url: "http://feeds.feedburner.com/PhdComics"
  processor: "rss"

- name: "commitstrip"
  url: "https://www.commitstrip.com/en/feed/"
  processor: "rss"

- name: "dilbert"
  url: "http://dilbert.com/feed"
  processor: "atom"

- name: "rllivejournal"
  url: "http://r-l.livejournal.com/data/rss"
  processor: "rss"
  normalizer: "livejournal"

- name: "nichtlustig-de"
  url: "http://static.nichtlustig.de/rss/nichtrss.rss"
  processor: "rss"

- name: "oatmeal"
  url: "http://feeds.feedburner.com/oatmealfeed"
  processor: "rss"

- name: "wumo"
  url: "http://wumo.com/wumo?view=rss"
  processor: "rss"

- name: "kamillalinder-medium"
  url: "https://medium.com/feed/@kamillalinder"
  processor: "rss"
  normalizer: "medium"

- name: "signalvnoise-medium"
  url: "https://m.signalvnoise.com/feed"
  processor: "rss"
  normalizer: "medium"

- name: "github-blog"
  url: "https://github.com/blog/all.atom"
  processor: "atom"

- name: "explosm-comics"
  url: "http://feeds.feedburner.com/Explosm"
  processor: "rss"

- name: "the-atlantic-photos"
  url: "http://feeds.feedburner.com/theatlantic/infocus"
  processor: "rss"

- name: "esquire-photos"
  url: "http://feeds.feedburner.com/esquire-ru"
  processor: "rss"

- name: "best-of-hacker-news"
  processor: "hacker_news"
  normalizer: "hacker_news"

- name: "reddit-worldnews"
  url: "https://www.reddit.com/r/worldnews/.rss"
  processor: "reddit"
  normalizer: "reddit"

- name: "avokado-fm"
  url: "http://tele.ga/avokado_fm/rss/"
  processor: "rss"
  normalizer: "telega"

- name: "ecologica"
  url: "https://vkrss.com/ecologicaspb?key=EW9tJd7ZI8iGBQyg"
  processor: "rss"
  normalizer: "vk_rss"

- name: "f28a"
  url: "http://floccinaucinihilipilificationa.tumblr.com/rss"
  processor: "rss"
  normalizer: "f28a"

- name: "agavr-today"
  url: "http://tele.ga/agavr_today/rss/"
  processor: "rss"
  normalizer: "telega"

- name: "vdud"
  url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCMCgOm8GZkHp8zJ6l7_hIuA"
  processor: "youtube"
  normalizer: "vdud"

- name: "parfenon"
  url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbhMGG0ZievPtK8mzLH5jhQ"
  processor: "youtube"
  normalizer: "youtube"

- name: "myjetpack"
  url: "http://myjetpack.tumblr.com/rss"
  processor: "rss"
  normalizer: "my_jetpack"

- name: "codinghorror"
  url: "http://feeds.feedburner.com/codinghorror"
  processor: "rss"
  normalizer: "coding_horror"

- name: "littlebigdetails"
  url: "http://littlebigdetails.com/rss"
  processor: "rss"
  normalizer: "little_big_details"
