---
- name: "xkcd"
  url: "http://xkcd.com/rss.xml"
  processor: "rss"

- name: "oglaf"
  url: "http://oglaf.com/feeds/rss/"
  processor: "rss"

- name: "phdcomics"
  url: "http://feeds.feedburner.com/PhdComics"
  processor: "rss"

- name: "commitstrip"
  url: "https://www.commitstrip.com/en/feed/"
  processor: "rss"

- name: "dilbert"
  url: "http://dilbert.com/feed"
  processor: "atom"

- name: "rllivejournal"
  url: "http://r-l.livejournal.com/data/rss"
  processor: "livejournal"

- name: "nichtlustig-de"
  url: "http://static.nichtlustig.de/rss/nichtrss.rss"
  processor: "rss"

- name: "oatmeal"
  url: "http://feeds.feedburner.com/oatmealfeed"
  processor: "rss"
