---
- name: "xkcd"
  url: "http://xkcd.com/rss.xml"
  processor: "rss"
  after: "2018-09-15T00:00:00+00:00"

- name: "oglaf"
  url: "http://oglaf.com/feeds/rss/"
  processor: "rss"
  normalizer: "oglaf"
  after: "2018-09-18T00:00:00+00:00"
  refresh_interval: 1800
  import_limit: 10

- name: "phdcomics"
  url: "http://feeds.feedburner.com/PhdComics"
  processor: "rss"
  after: "2018-09-18T00:00:00+00:00"

- name: "commitstrip"
  url: "https://www.commitstrip.com/en/feed/"
  processor: "rss"
  after: "2018-09-18T00:00:00+00:00"
  refresh_interval: 7200

- name: "dilbert"
  url: "http://dilbert.com/feed"
  processor: "atom"
  after: "2018-09-18T00:00:00+00:00"

- name: "rllivejournal"
  url: "http://r-l.livejournal.com/data/rss"
  processor: "rss"
  normalizer: "livejournal"
  after: "2018-09-18T00:00:00+00:00"

- name: "nichtlustig-de"
  url: "http://static.nichtlustig.de/rss/nichtrss.rss"
  processor: "rss"
  after: "2018-09-18T00:00:00+00:00"
  refresh_interval: 86400

- name: "oatmeal"
  url: "http://feeds.feedburner.com/oatmealfeed"
  processor: "rss"
  after: "2018-09-18T00:00:00+00:00"

- name: "wumo"
  url: "http://wumo.com/wumo?view=rss"
  processor: "rss"
  after: "2018-09-18T00:00:00+00:00"

- name: "kamillalinder-medium"
  url: "https://medium.com/feed/@kamillalinder"
  processor: "rss"
  normalizer: "medium"
  after: "2018-09-18T00:00:00+00:00"

- name: "signalvnoise-medium"
  url: "https://m.signalvnoise.com/feed"
  processor: "rss"
  normalizer: "medium"
  after: "2018-09-18T00:00:00+00:00"

- name: "github-blog"
  url: "https://github.com/blog/all.atom"
  processor: "atom"
  after: "2018-09-18T00:00:00+00:00"

- name: "explosm-comics"
  url: "http://feeds.feedburner.com/Explosm"
  processor: "rss"
  after: "2018-09-18T00:00:00+00:00"

- name: "the-atlantic-photos"
  url: "http://feeds.feedburner.com/theatlantic/infocus"
  processor: "rss"
  after: "2018-09-18T00:00:00+00:00"

# - name: "esquire-photos"
#   url: "http://feeds.feedburner.com/esquire-ru"
#   processor: "rss"
#   after: "2018-09-18T00:00:00+00:00"

- name: "best-of-hacker-news"
  loader: "null"
  processor: "hacker_news"
  normalizer: "hacker_news"
  after: "2018-09-18T20:00:00+00:00"
  refresh_interval: 600
  import_limit: 100

- name: "reddit-worldnews"
  url: "https://www.reddit.com/r/worldnews/.rss"
  processor: "reddit"
  normalizer: "reddit"
  after: "2018-09-18T20:00:00+00:00"
  refresh_interval: 600
  import_limit: 0

- name: "avokado-fm"
  url: "https://tele.ga/avokado_fm/rss/"
  processor: "rss"
  normalizer: "telega"
  after: "2018-09-18T00:00:00+00:00"

# - name: "ecologica"
#   url: "https://vkrss.com/ecologicaspb?key=EW9tJd7ZI8iGBQyg"
#   processor: "rss"
#   normalizer: "vk_rss"
#   after: "2018-09-18T00:00:00+00:00"
#   refresh_interval: 1200

- name: "f28a"
  # url: "http://floccinaucinihilipilificationa.tumblr.com/rss"
  url: http://feeds.feedburner.com/tumblr/bAzd
  processor: "rss"
  normalizer: "f28a"
  after: "2018-09-18T00:00:00+00:00"

- name: "agavr-today"
  url: "https://tele.ga/agavr_today/rss/"
  processor: "rss"
  normalizer: "agavr_today"
  after: "2018-09-18T00:00:00+00:00"

- name: "vdud"
  url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCMCgOm8GZkHp8zJ6l7_hIuA"
  processor: "youtube"
  normalizer: "vdud"
  after: "2018-09-18T00:00:00+00:00"

- name: "parfenon"
  url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbhMGG0ZievPtK8mzLH5jhQ"
  processor: "youtube"
  normalizer: "youtube"
  after: "2018-09-18T00:00:00+00:00"

- name: "myjetpack"
  # url: "http://myjetpack.tumblr.com/rss"
  url: "http://feeds.feedburner.com/tumblr/uOke"
  processor: "rss"
  normalizer: "my_jetpack"
  after: "2018-09-18T00:00:00+00:00"

- name: "codinghorror"
  url: "http://feeds.feedburner.com/codinghorror"
  processor: "rss"
  normalizer: "coding_horror"
  after: "2018-09-18T00:00:00+00:00"

- name: "little-big-details"
  # url: "http://littlebigdetails.com/rss"
  url: "http://feeds.feedburner.com/littlebigdetails/wJCD"
  processor: "rss"
  normalizer: "little_big_details"
  after: "2018-09-18T00:00:00+00:00"

- name: "blitz-and-chips"
  url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCRQEBFeG3lTMDEIUtQulzLg"
  processor: "youtube"
  normalizer: "youtube"
  after: "2018-09-18T00:00:00+00:00"

- name: "jimmydiresta"
  url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCiEk4xHBbz0hZNIBBpowdYQ"
  processor: "youtube"
  normalizer: "youtube"
  after: "2018-09-18T00:00:00+00:00"

- name: "confreaks"
  url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCWnPjmqvljcafA0z2U1fwKQ"
  processor: "youtube"
  normalizer: "youtube"
  after: "2018-09-18T00:00:00+00:00"

- name: "theycantalk"
  # url: "http://theycantalk.com/rss"
  url: "http://feeds.feedburner.com/theycantalk/xFcE"
  processor: "rss"
  normalizer: "theycantalk"
  after: "2018-09-18T00:00:00+00:00"

- name: "maremir"
  url: "http://maremir.org/feed/"
  processor: "rss"
  normalizer: "maremir"
  after: "2018-09-18T00:00:00+00:00"

- name: "sarahcandersen"
  url: "http://feeds.feedburner.com/sarahcandersen/koPM"
  processor: "rss"
  normalizer: "sarah_andersen"
  after: "2018-09-18T00:00:00+00:00"

- name: "newflux"
  url: "https://newflux.fr/feed/"
  processor: "feedjira"
  normalizer: "newflux"
  after: "2018-09-18T00:00:00+00:00"

- name: "blogdummi"
  url: "https://blogdummi.fr/feed/"
  processor: "wordpress"
  normalizer: "blogdummi"
  after: "2018-09-18T00:00:00+00:00"

- name: "waitbutwhy"
  url: "https://waitbutwhy.com/feed"
  processor: "wordpress"
  normalizer: "waitbutwhy"
  after: "2018-09-18T00:00:00+00:00"

- name: "savagechickens"
  url: "http://www.savagechickens.com/feed"
  processor: "wordpress"
  normalizer: "savagechickens"
  after: "2018-09-18T00:00:00+00:00"

- name: "poorlydrawnlines"
  url: "http://feeds.feedburner.com/PoorlyDrawnLines"
  processor: "feedjira"
  normalizer: "poorlydrawnlines"
  after: "2018-09-18T00:00:00+00:00"

- name: "kimchicuddles"
  url: "http://kimchicuddles.com/rss"
  processor: "feedjira"
  normalizer: "tumblr_normalizer"
  after: "2018-09-18T00:00:00+00:00"

# - name: "kimchicuddlesrus"
#   url: "http://kimchicuddlesrus.com"
#   processor: "kimchicuddlesrus"
#   normalizer: "kimchicuddlesrus"
#   after: "2018-09-18T00:00:00+00:00"

- name: "aerostatica"
  url: "https://feeds.feedburner.com/aerostatica"
  processor: "feedjira"
  normalizer: "aerostatica_normalizer"
  refresh_interval: 1200

# NOTE: Temporarily disabled
# - name: "rknalerts"
#   loader: "null"
#   processor: "rkn_alerts"
#   normalizer: "rkn_alerts"
#   refresh_interval: 600

- name: "algtestament"
  loader: "twitter"
  processor: "twitter"
  normalizer: "twitter"
  refresh_interval: 1200
  import_limit: 5
  options:
    twitter_user: "alg_testament"

- name: "extrafabulous"
  loader: "twitter"
  processor: "twitter"
  normalizer: "twitter"
  refresh_interval: 1200
  import_limit: 5
  options:
    twitter_user: "extrafabulous"
    only_with_attachments: true

- name: "bojackhorseman"
  loader: "twitter"
  processor: "twitter"
  normalizer: "twitter"
  refresh_interval: 1200
  import_limit: 5
  options:
    twitter_user: "bojackhorseman"

- name: "nextbigfuture"
  url: "https://www.nextbigfuture.com/feed"
  processor: "wordpress"
  normalizer: "nextbigfuture"
  refresh_interval: 1800
  import_limit: 5

- name: "nepozner"
  url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCNRYbltJXhf6DepS26-uSbQ"
  processor: "youtube"
  normalizer: "youtube"
  refresh_interval: 1800
  import_limit: 10

- name: "jakelikesonions"
  loader: "twitter"
  processor: "twitter"
  normalizer: "twitter"
  refresh_interval: 1200
  import_limit: 20
  options:
    twitter_user: "jakelikesonions"
    only_with_attachments: true

- name: "catscafe"
  loader: "twitter"
  processor: "twitter"
  normalizer: "twitter"
  refresh_interval: 1200
  import_limit: 20
  options:
    twitter_user: "CatsCafeComics"
    only_with_attachments: true

- name: hackernewsonion
  loader: "twitter"
  processor: "twitter"
  normalizer: "twitter"
  refresh_interval: 1200
  import_limit: 20
  options:
    twitter_user: "hackernewsonion"
    ignore_retweets: true

- name: bazar
  url: "https://meduza.io/rss/podcasts/knizhnyy-bazar"
  processor: "rss"
  normalizer: "bazar"
  refresh_interval: 1800
  import_limit: 10

- name: rework
  url: "https://rss.art19.com/rework"
  processor: "feedjira"
  normalizer: "rework"
  refresh_interval: 1800
  import_limit: 10

- name: "nathanwpyle"
  loader: "twitter"
  processor: "twitter"
  normalizer: "twitter"
  refresh_interval: 1200
  import_limit: 20
  options:
    twitter_user: "nathanwpyle"
    only_with_attachments: true
    ignore_retweets: true

- name: smbc
  url: "https://www.smbc-comics.com/comic/rss"
  processor: "rss"
  normalizer: "smbc"
  refresh_interval: 1800
  import_limit: 10
